config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "chatrooms#index"
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    @messages = Message.where(chatroom: @chatroom)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(params_message)
    @message.user = current_user
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message.chatroom = @chatroom
    if @message.save!
      ChatroomChannel.broadcast_to(
        @chatroom,
        json: {
          message: @message,
          user: @message.user
        }
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end

  end

  private

  def params_message
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatrooms/index.html.erb
<h1>Toutes les chatrooms</h1>
<ul>
  <% @chatrooms.each do |chatroom| %>
    <li>
      <%= link_to chatroom.name, chatroom_path(chatroom) %>
    </li>
  <% end %>
</ul>

app/views/chatrooms/show.html.erb
<div
  class="chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  data-chatroom-subscription-current-user-id-value="<%= current_user.id %>"
>
  <h1><%= @chatroom.name %></h1>
  <div class="messages" data-chatroom-subscription-target="messages">
    <% @messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>

  <%= simple_form_for [@chatroom, @message], html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }} do |f| %>
    <%= f.input :content,
    label: false,
    placeholder: "Message ##{@chatroom.name}" %>
    <%= f.submit "Envoyer" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatWebsocket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message <%= "my-message" if message.user == current_user %>">
  <div>
    <p class="message--nickname"><b><%= message.user.nickname %></b>
      -
      <i><%= message.created_at.strftime("%k:%M") %></i></p>

  </div>
  <p><%= message.content %></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flashes-notice" role="alert">
    <%= notice %>
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    >
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="flashes-alert" role="alert">
    <%= alert %>
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    >
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <ul id="navbar">
    <li class="nickname">Bienvenue
      <%= current_user.nickname if current_user %></li>
    <div class="navbar--menu">
      <li><%= link_to "Home", root_path %></li>
      <% if current_user %>
        <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </div>
  </ul>
</nav>